-- Seed data for the Bilt SQL practice. Do not edit this file.

DROP TABLE IF EXISTS merchants;
DROP TABLE IF EXISTS transactions;

CREATE TABLE merchants (
    merchant_name TEXT,
    merchant_code TEXT,
    category TEXT
);

CREATE TABLE transactions (
    id INTEGER PRIMARY KEY,
    user_id INTEGER,
    merchant_name TEXT,
    amount REAL,
    transacted_at TEXT
);

INSERT INTO merchants (merchant_name, merchant_code, category) VALUES
    ('Chipotle', 'CHIPOTLE', 'Restaurant'),
    ('Whole Foods', 'WHOLE_FOODS', 'Grocery'),
    ('Shake Shack', 'SHAKE_SHACK', 'restaurant'),
    ('  Sweetgreen  ', 'SWEETGREEN', '  Restaurant  ');

INSERT INTO transactions (id, user_id, merchant_name, amount, transacted_at) VALUES
    (1, 1, 'Chipotle', 10.90, '2024-01-15 12:00:00'),
    (2, 1, 'Unknown Cafe', 5.25, '2024-01-15 13:00:00'),
    (3, 1, 'Whole Foods', 8.40, '2024-01-15 14:00:00'),
    (4, 2, '  Chipotle  ', 10.00, '2024-01-16 12:00:00'),
    (5, 2, 'shake shack', 10.00, '2024-01-16 12:00:00'),
    (6, 2, 'Sweetgreen', 4.99, '2024-01-16 23:30:00'),
    (7, 1, 'Chipotle', 10.00, '2024-01-15T23:30:00-05:00');
